static char bin2c_LICENSE_Apache2_data [] = {
  "\n"  "                                 Apache License"  "\n"  "            "
  "               Version 2.0, January 2004"  "\n"  "                        ht"
  "tp://www.apache.org/licenses/"  "\n\n"  "   TERMS AND CONDITIONS FOR USE, "
  "REPRODUCTION, AND DISTRIBUTION"  "\n\n"  "   1. Definitions."  "\n\n"  " "
  "     "  "\x22"  "License"  "\x22"  " shall mean the terms and conditions for use"
  ", reproduction,"  "\n"  "      and distribution as defined by Sections 1 thr"
  "ough 9 of this document."  "\n\n"  "      "  "\x22"  "Licensor"  "\x22"  " sha"
  "ll mean the copyright owner or entity authorized by"  "\n"  "      the copyr"
  "ight owner that is granting the License."  "\n\n"  "      "  "\x22"  "Legal "
  "Entity"  "\x22"  " shall mean the union of the acting entity and all"  "\n"  " "
  "     other entities that control, are controlled by, or are under common"  "\n"
  "      control with that entity. For the purposes of this definition,"  "\n"  " "
  "     "  "\x22"  "control"  "\x22"  " means (i) the power, direct or indirect, to"
  " cause the"  "\n"  "      direction or management of such entity, whether by"
  " contract or"  "\n"  "      otherwise, or (ii) ownership of fifty percent (5"
  "0%) or more of the"  "\n"  "      outstanding shares, or (iii) beneficial ow"
  "nership of such entity."  "\n\n"  "      "  "\x22"  "You"  "\x22"  " (or "  "\x22"
  "Your"  "\x22"  ") shall mean an individual or Legal Entity"  "\n"  "      exer"
  "cising permissions granted by this License."  "\n\n"  "      "  "\x22"  "Sou"
  "rce"  "\x22"  " form shall mean the preferred form for making modifications,"  "\n"
  "      including but not limited to software source code, documentation"  "\n"
  "      source, and configuration files."  "\n\n"  "      "  "\x22"  "Object"  "\x22"
  " form shall mean any form resulting from mechanical"  "\n"  "      transform"
  "ation or translation of a Source form, including but"  "\n"  "      not limi"
  "ted to compiled object code, generated documentation,"  "\n"  "      and con"
  "versions to other media types."  "\n\n"  "      "  "\x22"  "Work"  "\x22"  " s"
  "hall mean the work of authorship, whether in Source or"  "\n"  "      Object"
  " form, made available under the License, as indicated by a"  "\n"  "      co"
  "pyright notice that is included in or attached to the work"  "\n"  "      (a"
  "n example is provided in the Appendix below)."  "\n\n"  "      "  "\x22"  "D"
  "erivative Works"  "\x22"  " shall mean any work, whether in Source or Object"  "\n"
  "      form, that is based on (or derived from) the Work and for which the"  "\n"
  "      editorial revisions, annotations, elaborations, or other modifications"
  "\n"  "      represent, as a whole, an original work of authorship. For the "
  "purposes"  "\n"  "      of this License, Derivative Works shall not include "
  "works that remain"  "\n"  "      separable from, or merely link (or bind by "
  "name) to the interfaces of,"  "\n"  "      the Work and Derivative Works the"
  "reof."  "\n\n"  "      "  "\x22"  "Contribution"  "\x22"  " shall mean any wor"
  "k of authorship, including"  "\n"  "      the original version of the Work a"
  "nd any modifications or additions"  "\n"  "      to that Work or Derivative "
  "Works thereof, that is intentionally"  "\n"  "      submitted to Licensor fo"
  "r inclusion in the Work by the copyright owner"  "\n"  "      or by an indiv"
  "idual or Legal Entity authorized to submit on behalf of"  "\n"  "      the c"
  "opyright owner. For the purposes of this definition, "  "\x22"  "submitted"  "\x22"
  "\n"  "      means any form of electronic, verbal, or written communication "
  "sent"  "\n"  "      to the Licensor or its representatives, including but no"
  "t limited to"  "\n"  "      communication on electronic mailing lists, sourc"
  "e code control systems,"  "\n"  "      and issue tracking systems that are m"
  "anaged by, or on behalf of, the"  "\n"  "      Licensor for the purpose of d"
  "iscussing and improving the Work, but"  "\n"  "      excluding communication"
  " that is conspicuously marked or otherwise"  "\n"  "      designated in writ"
  "ing by the copyright owner as "  "\x22"  "Not a Contribution."  "\x22\n\n"  " "
  "     "  "\x22"  "Contributor"  "\x22"  " shall mean Licensor and any individual "
  "or Legal Entity"  "\n"  "      on behalf of whom a Contribution has been rec"
  "eived by Licensor and"  "\n"  "      subsequently incorporated within the Wo"
  "rk."  "\n\n"  "   2. Grant of Copyright License. Subject to the terms and "
  "conditions of"  "\n"  "      this License, each Contributor hereby grants to"
  " You a perpetual,"  "\n"  "      worldwide, non-exclusive, no-charge, royalt"
  "y-free, irrevocable"  "\n"  "      copyright license to reproduce, prepare D"
  "erivative Works of,"  "\n"  "      publicly display, publicly perform, subli"
  "cense, and distribute the"  "\n"  "      Work and such Derivative Works in S"
  "ource or Object form."  "\n\n"  "   3. Grant of Patent License. Subject to"
  " the terms and conditions of"  "\n"  "      this License, each Contributor h"
  "ereby grants to You a perpetual,"  "\n"  "      worldwide, non-exclusive, no"
  "-charge, royalty-free, irrevocable"  "\n"  "      (except as stated in this "
  "section) patent license to make, have made,"  "\n"  "      use, offer to sel"
  "l, sell, import, and otherwise transfer the Work,"  "\n"  "      where such "
  "license applies only to those patent claims licensable"  "\n"  "      by suc"
  "h Contributor that are necessarily infringed by their"  "\n"  "      Contrib"
  "ution(s) alone or by combination of their Contribution(s)"  "\n"  "      wit"
  "h the Work to which such Contribution(s) was submitted. If You"  "\n"  "    "
  "  institute patent litigation against any entity (including a"  "\n"  "     "
  " cross-claim or counterclaim in a lawsuit) alleging that the Work"  "\n"  " "
  "     or a Contribution incorporated within the Work constitutes direct"  "\n"
  "      or contributory patent infringement, then any patent licenses"  "\n"  " "
  "     granted to You under this License for that Work shall terminate"  "\n"  " "
  "     as of the date such litigation is filed."  "\n\n"  "   4. Redistribut"
  "ion. You may reproduce and distribute copies of the"  "\n"  "      Work or D"
  "erivative Works thereof in any medium, with or without"  "\n"  "      modifi"
  "cations, and in Source or Object form, provided that You"  "\n"  "      meet"
  " the following conditions:"  "\n\n"  "      (a) You must give any other re"
  "cipients of the Work or"  "\n"  "          Derivative Works a copy of this L"
  "icense; and"  "\n\n"  "      (b) You must cause any modified files to carr"
  "y prominent notices"  "\n"  "          stating that You changed the files; a"
  "nd"  "\n\n"  "      (c) You must retain, in the Source form of any Derivat"
  "ive Works"  "\n"  "          that You distribute, all copyright, patent, tra"
  "demark, and"  "\n"  "          attribution notices from the Source form of t"
  "he Work,"  "\n"  "          excluding those notices that do not pertain to a"
  "ny part of"  "\n"  "          the Derivative Works; and"  "\n\n"  "      ("
  "d) If the Work includes a "  "\x22"  "NOTICE"  "\x22"  " text file as part of it"
  "s"  "\n"  "          distribution, then any Derivative Works that You distri"
  "bute must"  "\n"  "          include a readable copy of the attribution noti"
  "ces contained"  "\n"  "          within such NOTICE file, excluding those no"
  "tices that do not"  "\n"  "          pertain to any part of the Derivative W"
  "orks, in at least one"  "\n"  "          of the following places: within a N"
  "OTICE text file distributed"  "\n"  "          as part of the Derivative Wor"
  "ks; within the Source form or"  "\n"  "          documentation, if provided "
  "along with the Derivative Works; or,"  "\n"  "          within a display gen"
  "erated by the Derivative Works, if and"  "\n"  "          wherever such thir"
  "d-party notices normally appear. The contents"  "\n"  "          of the NOTI"
  "CE file are for informational purposes only and"  "\n"  "          do not mo"
  "dify the License. You may add Your own attribution"  "\n"  "          notice"
  "s within Derivative Works that You distribute, alongside"  "\n"  "          "
  "or as an addendum to the NOTICE text from the Work, provided"  "\n"  "      "
  "    that such additional attribution notices cannot be construed"  "\n"  "  "
  "        as modifying the License."  "\n\n"  "      You may add Your own co"
  "pyright statement to Your modifications and"  "\n"  "      may provide addit"
  "ional or different license terms and conditions"  "\n"  "      for use, repr"
  "oduction, or distribution of Your modifications, or"  "\n"  "      for any s"
  "uch Derivative Works as a whole, provided Your use,"  "\n"  "      reproduct"
  "ion, and distribution of the Work otherwise complies with"  "\n"  "      the"
  " conditions stated in this License."  "\n\n"  "   5. Submission of Contrib"
  "utions. Unless You explicitly state otherwise,"  "\n"  "      any Contributi"
  "on intentionally submitted for inclusion in the Work"  "\n"  "      by You t"
  "o the Licensor shall be under the terms and conditions of"  "\n"  "      thi"
  "s License, without any additional terms or conditions."  "\n"  "      Notwit"
  "hstanding the above, nothing herein shall supersede or modify"  "\n"  "     "
  " the terms of any separate license agreement you may have executed"  "\n"  " "
  "     with Licensor regarding such Contributions."  "\n\n"  "   6. Trademar"
  "ks. This License does not grant permission to use the trade"  "\n"  "      n"
  "ames, trademarks, service marks, or product names of the Licensor,"  "\n"  " "
  "     except as required for reasonable and customary use in describing the"  "\n"
  "      origin of the Work and reproducing the content of the NOTICE file."  "\n"
  "\n"  "   7. Disclaimer of Warranty. Unless required by applicable law or"  "\n"
  "      agreed to in writing, Licensor provides the Work (and each"  "\n"  "  "
  "    Contributor provides its Contributions) on an "  "\x22"  "AS IS"  "\x22"  " "
  "BASIS,"  "\n"  "      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either e"
  "xpress or"  "\n"  "      implied, including, without limitation, any warrant"
  "ies or conditions"  "\n"  "      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY"
  ", or FITNESS FOR A"  "\n"  "      PARTICULAR PURPOSE. You are solely respons"
  "ible for determining the"  "\n"  "      appropriateness of using or redistri"
  "buting the Work and assume any"  "\n"  "      risks associated with Your exe"
  "rcise of permissions under this License."  "\n\n"  "   8. Limitation of Li"
  "ability. In no event and under no legal theory,"  "\n"  "      whether in to"
  "rt (including negligence), contract, or otherwise,"  "\n"  "      unless req"
  "uired by applicable law (such as deliberate and grossly"  "\n"  "      negli"
  "gent acts) or agreed to in writing, shall any Contributor be"  "\n"  "      "
  "liable to You for damages, including any direct, indirect, special,"  "\n"  " "
  "     incidental, or consequential damages of any character arising as a"  "\n"
  "      result of this License or out of the use or inability to use the"  "\n"
  "      Work (including but not limited to damages for loss of goodwill,"  "\n"
  "      work stoppage, computer failure or malfunction, or any and all"  "\n"  " "
  "     other commercial damages or losses), even if such Contributor"  "\n"  " "
  "     has been advised of the possibility of such damages."  "\n\n"  "   9."
  " Accepting Warranty or Additional Liability. While redistributing"  "\n"  " "
  "     the Work or Derivative Works thereof, You may choose to offer,"  "\n"  " "
  "     and charge a fee for, acceptance of support, warranty, indemnity,"  "\n"
  "      or other liability obligations and/or rights consistent with this"  "\n"
  "      License. However, in accepting such obligations, You may act only"  "\n"
  "      on Your own behalf and on Your sole responsibility, not on behalf"  "\n"
  "      of any other Contributor, and only if You agree to indemnify,"  "\n"  " "
  "     defend, and hold each Contributor harmless for any liability"  "\n"  " "
  "     incurred by, or claims asserted against, such Contributor by reason"  "\n"
  "      of your accepting any such warranty or additional liability."  "\n\n"
  "   END OF TERMS AND CONDITIONS"  "\n\n"  "   APPENDIX: How to apply the Ap"
  "ache License to your work."  "\n\n"  "      To apply the Apache License to"
  " your work, attach the following"  "\n"  "      boilerplate notice, with the"
  " fields enclosed by brackets "  "\x22"  "[]"  "\x22\n"  "      replaced with y"
  "our own identifying information. (Don't include"  "\n"  "      the brackets!"
  ")  The text should be enclosed in the appropriate"  "\n"  "      comment syn"
  "tax for the file format. We also recommend that a"  "\n"  "      file or cla"
  "ss name and description of purpose be included on the"  "\n"  "      same "  "\x22"
  "printed page"  "\x22"  " as the copyright notice for easier"  "\n"  "      ide"
  "ntification within third-party archives."  "\n\n"  "   Copyright [yyyy] [n"
  "ame of copyright owner]"  "\n\n"  "   Licensed under the Apache License, V"
  "ersion 2.0 (the "  "\x22"  "License"  "\x22"  ");"  "\n"  "   you may not use th"
  "is file except in compliance with the License."  "\n"  "   You may obtain a "
  "copy of the License at"  "\n\n"  "       http://www.apache.org/licenses/LI"
  "CENSE-2.0"  "\n\n"  "   Unless required by applicable law or agreed to in "
  "writing, software"  "\n"  "   distributed under the License is distributed o"
  "n an "  "\x22"  "AS IS"  "\x22"  " BASIS,"  "\n"  "   WITHOUT WARRANTIES OR COND"
  "ITIONS OF ANY KIND, either express or implied."  "\n"  "   See the License f"
  "or the specific language governing permissions and"  "\n"  "   limitations u"
  "nder the License."  "\n"};
static const long bin2c_LICENSE_Apache2_size = 11358;

